[2020-03-11 16:46:04] WARN  org.springframework.context.support.AbstractApplicationContext 557 refresh - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'addressController': Unsatisfied dependency expressed through field 'iAddressService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'addressServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'addressMapper' defined in file [D:\IdeaProjects\myspringcloud\myspringcloud-provider\target\classes\com\cloud\mapper\AddressMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is java.sql.SQLException: The connection property 'zeroDateTimeBehavior' only accepts values of the form: 'exception', 'round' or 'convertToNull'. The value 'CONVERT_TO_NULL' is not in this set.
[2020-03-11 16:55:08] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 17:19:10] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 17:19:58] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 17:20:07] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 17:20:08] WARN  org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer 60 startServer - Unable to start LiveReload server
[2020-03-11 18:18:46] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 18:22:41] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 18:24:59] WARN  com.baomidou.mybatisplus.core.toolkit.TableInfoHelper 255 initTableFields - Warn: Could not find @TableId in Class: com.cloud.myspringcloud.entity.Address.
[2020-03-11 20:05:26] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 20:05:26] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 20:09:09] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 20:09:09] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 20:09:13] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-11 20:09:13] WARN  com.netflix.discovery.DiscoveryClient$1 290 get - Using default backup registry implementation which does not do anything.
[2020-03-11 20:09:15] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-11 20:09:15] WARN  com.netflix.discovery.DiscoveryClient 831 register - DiscoveryClient_MYSPRINGCLOUD-ADDRESS/192.168.3.217:9090 - registration failed Cannot execute request on any known server com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829) [eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) [eureka-client-1.9.8.jar:1.9.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

[2020-03-11 20:09:15] WARN  com.netflix.discovery.InstanceInfoReplicator 125 run - There was a problem with the instance info replicator com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) [eureka-client-1.9.8.jar:1.9.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

[2020-03-11 20:09:56] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 20:09:56] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 21:22:34] WARN  com.netflix.discovery.DiscoveryClient$3 1303 notify - Saw local status change event StatusChangeEvent [timestamp=1583932954321, current=DOWN, previous=UP]
[2020-03-11 21:22:41] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 21:42:27] WARN  org.springframework.boot.actuate.endpoint.EndpointId 131 logWarning - Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
[2020-03-11 21:42:28] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 21:42:31] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 21:44:08] WARN  com.netflix.discovery.DiscoveryClient$3 1303 notify - Saw local status change event StatusChangeEvent [timestamp=1583934248809, current=DOWN, previous=UP]
[2020-03-11 21:44:16] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 21:46:40] WARN  com.netflix.discovery.DiscoveryClient$3 1303 notify - Saw local status change event StatusChangeEvent [timestamp=1583934400927, current=DOWN, previous=UP]
[2020-03-11 21:46:48] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 21:49:37] WARN  com.netflix.discovery.DiscoveryClient$3 1303 notify - Saw local status change event StatusChangeEvent [timestamp=1583934577149, current=DOWN, previous=UP]
[2020-03-11 21:49:43] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 23:03:31] WARN  org.springframework.boot.actuate.endpoint.EndpointId 131 logWarning - Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
[2020-03-11 23:03:33] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-11 23:03:35] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-12 15:38:29] WARN  org.springframework.boot.actuate.endpoint.EndpointId 131 logWarning - Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
[2020-03-12 15:38:31] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-12 15:38:34] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-13 00:26:41] WARN  org.springframework.boot.actuate.endpoint.EndpointId 131 logWarning - Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
[2020-03-13 00:26:45] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-13 00:26:48] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-13 00:26:53] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-13 00:26:54] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-13 00:26:55] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-13 00:26:55] WARN  com.netflix.discovery.DiscoveryClient$1 290 get - Using default backup registry implementation which does not do anything.
[2020-03-13 00:26:56] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-13 00:26:57] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-13 00:26:59] WARN  com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient 130 execute - Request execution failed with message: java.net.ConnectException: Connection refused: connect
[2020-03-13 00:26:59] WARN  com.netflix.discovery.DiscoveryClient 831 register - DiscoveryClient_MYSPRINGCLOUD-ADDRESS/192.168.3.217:9090 - registration failed Retry limit reached; giving up on completing the request com.netflix.discovery.shared.transport.TransportException: Retry limit reached; giving up on completing the request
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:139) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829) [eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) [eureka-client-1.9.8.jar:1.9.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

[2020-03-13 00:26:59] WARN  com.netflix.discovery.InstanceInfoReplicator 125 run - There was a problem with the instance info replicator com.netflix.discovery.shared.transport.TransportException: Retry limit reached; giving up on completing the request
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:139) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:829) ~[eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121) [eureka-client-1.9.8.jar:1.9.8]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) [eureka-client-1.9.8.jar:1.9.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

[2020-03-13 00:27:37] WARN  org.springframework.boot.actuate.endpoint.EndpointId 131 logWarning - Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
[2020-03-13 00:27:38] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
[2020-03-13 00:27:40] WARN  com.netflix.config.sources.URLConfigurationSource 121 <init> - No URLs will be polled as dynamic configuration sources.
